controller_frequency:       40.0    # default: 20.0
planner_patience:           5.0     # default: 5.0
controller_patience:        15.0    # default: 15.0
planner_frequency:          1.0
recovery_behaviors: [{name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}, {name: rotate_recovery, type: rotate_recovery/RotateRecovery}]
conservative_reset_dist:    1.0
clearing_radius:            0.0
