controller_list:
  - name: fake_arm_controller
    joints:
      - linear_joint
      - j2s7s300_joint_1
      - j2s7s300_joint_2
      - j2s7s300_joint_3
      - j2s7s300_joint_4
      - j2s7s300_joint_5
      - j2s7s300_joint_6
      - j2s7s300_joint_7
  - name: fake_gripper_controller
    joints:
      - robotiq_85_left_knuckle_joint
  - name: fake_head_controller
    joints:
      - pan_joint
      - tilt_joint