GlobalPlanner:
  lethal_cost:                  253   #default: 253
  neutral_cost:                 50    #default: 50
  orientation_mode:             1     #default: 1-Forward
  publish_potential:            false #default: false

EBandPlannerROS:
  differential_drive: true
  footprint: [[0.35,0.275809],[0.62,0.0],[0.35,-0.275809],[-0.365164,-0.275809],[-0.365164,0.275809]]
  # velocity limits
  max_vel_lin: 0.65
  max_vel_th: 0.65
  min_vel_lin: 0.1
  min_in_place_vel_th: 0.1

  # goal tolerance
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1

  #eband parameters
  eband_disallow_hysteresis: false

TrajectoryPlannerROS:
  max_vel_x: 0.45
  min_vel_x: 0.1
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.2

  acc_lim_th: 2.0
  acc_lim_x: 2.0
  acc_lim_y: 2.0

  sim_time: 3.0

  pdist_scale: 0.6
  gdist_scale: 0.8
  occdist_scale: 0.01

  holonomic_robot: true
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
    
  latch_xy_goal_tolerance: true

DWAPlannerROS:
  # Robot Configuration Parameters
  acc_lim_x:                    1.5     #default 2.5    
  acc_lim_y:                    1.5     #default 2.5
  acc_lim_th:                   1.2     #default 3.2
  max_trans_vel:                0.25     #default 0.55
  min_trans_vel:                0.01    #default 0.1
  max_vel_x:                    0.25     #default 0.55
  min_vel_x:                    0.0     #default 0.0
  max_vel_y:                    0.05     #default 0.1
  min_vel_y:                   -0.05     #default -0.1
  max_rot_vel:                  0.2     #default 1.0
  min_rot_vel:                  0.2    #default 0.4
  rot_stopped_vel:              0.01
  trans_stopped_vel:            0.01

  # Goal Tolerance Parameters
  yaw_goal_tolerance:           0.1    #default 0.05
  xy_goal_tolerance:            0.2     #default 0.1
  latch_xy_goal_tolerance:      true    #default false

  # Forward Simulation Parameters
  sim_time:                     1.7     #default 1.7
  sim_granularity:              0.017   #default 0.025
  angular_sim_granularity:      0.017   #default 0.025
  sim_period:                   0.1
  vx_samples:                   5       #default 3
  vy_samples:                   3       #default 3
  vtheta_samples:               10      #default 10
  controller_frequency:         40.0    #default 20.0
  penalize_negative_x:          true    #default true Note should have a rearward laser scanner to set this to false

  # Trajectory scoring parameters
  # The weighting for how much the controller should stay close to the path it was given
  path_distance_bias:             32.0    #default 32.0
  # The weighting for how much the controller should attempt to reach its local goal, also controls speed
  goal_distance_bias:             24.0    #default 24.0
  # The weighting for how much the controller should attempt to avoid obstacles
  occdist_scale:                  0.01     #default 0.01
  # The distance from the center point of the robot to place an additional scoring point, in meters
  forward_point_distance:         0.30     #default 0.325
  # The amount of time that the robot must stThe absolute value of the veolicty at which to start scaling the robot's footprint,
  # in m/sop before a collision in order for a trajectory to be considered valid in seconds
  stop_time_buffer:               0.2     #default 0.2
  # The absolute value of the veolicty at which to start scaling the robot's footprint, in m/s
  scaling_speed:                  0.25    #default 0.25
  # The maximum factor to scale the robot's footprint by
  max_scaling_factor:             0.2     #default 0.2

  # Oscillation Prevention Parameters
  # How far the robot must travel in meters before oscillation flags are reset
  oscillation_reset_dist:       0.05    #default 0.05

  # Global Plan Parameters
  prune_plan:                   true    #default true
  
  holonomic_robot: false


TebLocalPlannerROS:

 odom_topic: /vector/odometry/local_filtered
 map_frame: /odom

 # Trajectory

 teb_autosize: True
 dt_ref: 0.47
 dt_hysteresis: 0.15
 global_plan_overwrite_orientation: True
 max_global_plan_lookahead_dist: 3.0
 feasibility_check_no_poses: 5

 # Robot

 max_vel_x: 0.4
 max_vel_x_backwards: 0.2
 max_vel_theta: 0.3
 acc_lim_x: 0.3
 acc_lim_theta: 0.3
 min_turning_radius: 0.0
 footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
   type: "polygon"
   vertices: [[0.45,0.275809],[0.72,0],[0.45,-0.275809],[-0.365164,-0.275809],[-0.365164,0.275809]]

 # GoalTolerance
 xy_goal_tolerance: 0.2
 yaw_goal_tolerance: 0.1
 free_goal_vel: False

 # Obstacles

 min_obstacle_dist: 0.17
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.0
 obstacle_poses_affected: 30
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5

 # Optimization

 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1
 weight_max_vel_x: 2
 weight_max_vel_theta: 10
 weight_acc_lim_x: 1
 weight_acc_lim_theta: 3
 weight_kinematics_nh: 1000
 weight_kinematics_forward_drive: 1
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 1
 weight_obstacle: 50
 weight_dynamic_obstacle: 10 # not in use yet
 alternative_time_cost: False # not in use yet

 # Homotopy Class Planner

 enable_homotopy_class_planning: True
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 4
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False

